import { AbpHttpInterceptor, RefreshTokenService, AbpHttpConfigurationService } from 'abp-ng2-module';
import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { NgModule } from '@angular/core';
import * as ApiServiceProxies from './service-proxies';
import { ZeroRefreshTokenService } from '@account/auth/zero-refresh-token.service';
import { ZeroTemplateHttpConfigurationService } from './zero-template-http-configuration.service';

@NgModule({
    providers: [
        ApiServiceProxies.BillingsServiceProxy,        
        ApiServiceProxies.ContactsServiceProxy,        
        ApiServiceProxies.ChatStatusesServiceProxy,        
        ApiServiceProxies.ContactStatusesServiceProxy,        
        ApiServiceProxies.ReceiptsServiceProxy,        
        ApiServiceProxies.ReceiptDetailsServiceProxy,        
        ApiServiceProxies.BanksServiceProxy,        
        ApiServiceProxies.PaymentMethodsServiceProxy,        
        ApiServiceProxies.TenantServicesServiceProxy,        
        ApiServiceProxies.AccountBillingsServiceProxy,        
        ApiServiceProxies.CurrenciesServiceProxy,        
        ApiServiceProxies.InfoSeedServicesServiceProxy,        
        ApiServiceProxies.ServiceFrquenciesServiceProxy,        
        ApiServiceProxies.ServiceStatusesServiceProxy,        
        ApiServiceProxies.ServiceTypesServiceProxy,        
        ApiServiceProxies.TemplateMessagesServiceProxy,        
        ApiServiceProxies.GendersServiceProxy,
        ApiServiceProxies.CitiesServiceProxy,
        ApiServiceProxies.AreasServiceProxy,
        ApiServiceProxies.MenuDetailsServiceProxy,
        ApiServiceProxies.MenusServiceProxy,
        ApiServiceProxies.MenuItemStatusesServiceProxy,
        ApiServiceProxies.ItemsServiceProxy,
        ApiServiceProxies.ItemCategoryServiceProxy,
        ApiServiceProxies.AuditLogServiceProxy,
        ApiServiceProxies.CachingServiceProxy,
        ApiServiceProxies.ChatServiceProxy,
        ApiServiceProxies.CommonLookupServiceProxy,
        ApiServiceProxies.EditionServiceProxy,
        ApiServiceProxies.FriendshipServiceProxy,
        ApiServiceProxies.HostSettingsServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.LanguageServiceProxy,
        ApiServiceProxies.NotificationServiceProxy,
        ApiServiceProxies.OrganizationUnitServiceProxy,
        ApiServiceProxies.PermissionServiceProxy,
        ApiServiceProxies.ProfileServiceProxy,
        ApiServiceProxies.RoleServiceProxy,
        ApiServiceProxies.SessionServiceProxy,
        ApiServiceProxies.TenantServiceProxy,
        ApiServiceProxies.ItemsServiceProxy,
        ApiServiceProxies.TenantDashboardServiceProxy,
        ApiServiceProxies.TenantSettingsServiceProxy,
        ApiServiceProxies.TimingServiceProxy,
        ApiServiceProxies.UserServiceProxy,
        ApiServiceProxies.UserLinkServiceProxy,
        ApiServiceProxies.UserLoginServiceProxy,
        ApiServiceProxies.WebLogServiceProxy,
        ApiServiceProxies.AccountServiceProxy,
        ApiServiceProxies.TokenAuthServiceProxy,
        ApiServiceProxies.TenantRegistrationServiceProxy,
        ApiServiceProxies.HostDashboardServiceProxy,
        ApiServiceProxies.PaymentServiceProxy,
        ApiServiceProxies.DemoUiComponentsServiceProxy,
        ApiServiceProxies.InvoiceServiceProxy,
        ApiServiceProxies.SubscriptionServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.UiCustomizationSettingsServiceProxy,
        ApiServiceProxies.PayPalPaymentServiceProxy,
        ApiServiceProxies.StripePaymentServiceProxy,
        ApiServiceProxies.DashboardCustomizationServiceProxy,
        ApiServiceProxies.WebhookEventServiceProxy,
        ApiServiceProxies.WebhookSubscriptionServiceProxy,
        ApiServiceProxies.WebhookSendAttemptServiceProxy,
        ApiServiceProxies.UserDelegationServiceProxy,
        ApiServiceProxies.DynamicPropertyServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyDefinitionServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyServiceProxy,
        ApiServiceProxies.DynamicPropertyValueServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyValueServiceProxy,
        ApiServiceProxies.CustomerBehaviourServiceProxy,
        ApiServiceProxies.OrderOfferServiceProxy,
        ApiServiceProxies.LocationsServiceProxy,
        ApiServiceProxies.GeneralServiceProxy,

        { provide: RefreshTokenService, useClass: ZeroRefreshTokenService },
        { provide: AbpHttpConfigurationService, useClass: ZeroTemplateHttpConfigurationService },
        { provide: HTTP_INTERCEPTORS, useClass: AbpHttpInterceptor, multi: true }
    ]
})
export class ServiceProxyModule { }
